---
apiVersion: v1
kind: Namespace
metadata:
  name: '{{APP_NAME}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{APP_NAME}}'
  name: '{{APP_NAME}}'
  labels:
    app.kubernetes.io/name: '{{APP_NAME}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{APP_NAME}}'
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{APP_NAME}}'
    spec:
      containers:
      - image: '{{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{APP_NAME}}:{{IMAGE_TAG}}'
        imagePullPolicy: Always
        name: '{{APP_NAME}}'
        ports:
        - containerPort: 3000
        env:
        - name: IMAGE_URL
          value: https://dz0gfe2kzeqxy.cloudfront.net/'{{APP_NAME}}'-world-cup.jpeg
            
---
apiVersion: v1
kind: Service
metadata:
  namespace: '{{APP_NAME}}'
  name: '{{APP_NAME}}'
  labels:
    app.kubernetes.io/name: '{{APP_NAME}}'
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: '{{APP_NAME}}'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: '{{APP_NAME}}'
  name: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/name: '{{APP_NAME}}'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: '{{APP_NAME}}'
              port:
                number: 80
