apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-world
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "256m"
            memory: "512Mi"
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  namespace: hello-world
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hello-world
  name: nginx-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
spec:
  ingressClassName: "alb"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
