name: Deploy app1

env:
  AWS_REGION: 'ap-southeast-2'
  AWS_ACCOUNT_ID: '590183968070'
  AWS_OIDC_ROLE: 'arn:aws:iam::590183968070:role/github-action-app-role-ap-southeast-2'
  
  ROLLBACK: 'false'
  DESTROY: 'false'

on:
  workflow_dispatch:
    inputs:
      name:
        default: Debigging...
        description: "Running workflow manually"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read 

jobs:
  main:
    name: main
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: AWS OIDC Provider
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_OIDC_ROLE }}
          role-session-name: github-actions-app

      - name: Build Docker Image
        run: make build

      - name: Scan Docker Image
        run: make scan

      - name: Deploy App
        run: make deploy
        if: ${{ env.DESTROY == 'false' && env.ROLLBACK == 'false' }}

      - name: Rollback App
        run: make rollback
        if: ${{ env.DESTROY == 'false' && env.ROLLBACK == 'true' }}

      - name: Destroy App
        run: make destroy
        if: ${{ env.DESTROY == 'true' }}
